### ISSUE TITLE
Timeslider should only be visible when at least one layer with time support is active

### ISSUE THREAD

**Issue by Schpidi** [EOX-A/EOxClient#8]

**Comment by santilland** [comment]
First implementation for this is available in the timeslider branch pushed in 8af5624f488b3118597e2bfda13bb30d89bcfb4c
But there are some things to consider:
- When deselecting a layer (product) and the timslider is disabled, what selection and extent should be shown when reopening (selecting a layer)?

**Comment by santilland** [comment]
Functionality was now added to master
